### PR TITLE
ISSUE-9: Move internalOptions.facade to public api (fix #9)

### LINKED ISSUE #9: Move internalOptions.facade to public api
Well, I want to use your package with my own FS facade functions, for example, [scandir-native](https://github.com/mrmlnc/scandir-native). It seems that it would be useful not only me. For example, if you want to use this package for walk directories in the remote drive.

### PR DESCRIPTION
**Pull request by mrmlnc**
### Links

#9

### What is this?

  * Ability to override default Node.js FileSystem API's.

### CODE REVIEW

**Comment by mrmlnc** [comment]
Hm, strange that tests for `options.filter` is failed. Well, will be fixed soon.

**Comment by BigstickCarpet** [comment]
@mrmlnc - Great work, as always!  Thanks for always including tests, comments, and documentation with all of your PRs.  I **really** appreciate that.

I like your approach to this, but I'd suggest a couple minor changes...  

First, rather than merging the `options.facade` and `internalOptions.facade` in three places (`lib/sync/index.js`, `lib/async/index.js`, and `lib/steam/index.js`), I think it would be better to do it inside the `normalizeOptions.js` function.  That function accepts the `options` and `internalOptions` objects, does whatever logic is necessary to merge the two, and returns a merged and normalized object.

Secondly, I think it would be simpler to have the `fs` methods directly on `options.facade`, rather than having separate `options.facade.sync` and `options.facade.async` properties.  Any given `readdir-enhanced` method is _only_ sync or async, so it wouldn't ever make sense to pass _both_ sync _and_ async facades.  It'll be up to the user to know whether they're calling a synchronous or asynchronous method and pass the correct facade for it.

What do you think?  These are pretty minor changes, and now I realize that I probably could have done them in the time it took to write all of this. 😀

**Comment by BigstickCarpet** [comment]
Also, I've invited you to be a contributor on this project, since you consistently do such good work on it. 👍

**Comment by mrmlnc** [comment]
Yeap, I'll think about it very soon.

**Comment by mrmlnc** [comment]
Well, push alternative way :)

**Comment by mrmlnc** [comment]
@BigstickCarpet ping :smiley:

**Comment by BigstickCarpet** [comment]
@mrmlnc - Sorry.  I've had zero spare time for the past couple of weeks.  But I'm off next week for the holidays, so I'm planning to catch-up on stuff like this.  Sorry for the delay :(

**Comment by BigstickCarpet** [comment]
Ok, @mrmlnc, I _finally_ got some free time to merge this PR.  Thanks again for the great work!  I'll make the [changes that I mentioned above](https://github.com/BigstickCarpet/readdir-enhanced/pull/10#issuecomment-348964846) and then publish a new version to NPM.  Shouldn't take more than a couple hours.

**Comment by BigstickCarpet** [comment]
This fix has been released in [version 2.2.0](https://github.com/BigstickCarpet/readdir-enhanced/blob/master/CHANGELOG.md)

**Pull request merged**
